import type { Registration as PrismaRegistration } from "@/lib/generated/prisma/client";
import type {
  ApplicationCategory,
  CompanySize,
  CompanyType,
  Currency,
  Locale,
  Registration,
} from "@/lib/types";

// Prisma row <-> Registration DTO. Registration is a flat record (no Json columns
// beyond scalar arrays); transforms here are limited to undef-nulling optionals,
// DateTime <-> ISO string, and a default for the nullable status enum on read.

const undef = <T,>(v: T | null): T | undefined => (v == null ? undefined : v);

/** Prisma row -> Registration DTO (the shape the UI consumes). */
export function registrationToDTO(r: PrismaRegistration): Registration {
  return {
    id: r.id,
    reference: r.reference,
    status: r.status ?? "submitted",
    legalName: r.legalName,
    tradingName: undef(r.tradingName),
    companyType: r.companyType as CompanyType,
    companySubtype: undef(r.companySubtype),
    website: undef(r.website),
    country: r.country,
    countryCode: r.countryCode,
    region: undef(r.region),
    city: r.city,
    address: undef(r.address),
    postalCode: undef(r.postalCode),
    vatNumber: undef(r.vatNumber),
    registrationNumber: undef(r.registrationNumber),
    mainActivity: undef(r.mainActivity),
    companySize: undef(r.companySize as CompanySize | null),
    marketsServed: r.marketsServed,
    preferredLanguage: r.preferredLanguage as Locale,
    preferredCurrency: r.preferredCurrency as Currency,
    timezone: undef(r.timezone),
    contactFirstName: r.contactFirstName,
    contactLastName: r.contactLastName,
    contactJobTitle: undef(r.contactJobTitle),
    contactDepartment: undef(r.contactDepartment),
    contactEmail: r.contactEmail,
    contactPhone: undef(r.contactPhone),
    contactMobile: undef(r.contactMobile),
    contactLanguage: undef(r.contactLanguage as Locale | null),
    reason: undef(r.reason),
    existingContactPerson: undef(r.existingContactPerson),
    intendedApplications: r.intendedApplications as ApplicationCategory[],
    productCategories: r.productCategories as ApplicationCategory[],
    samplesRequested: undef(r.samplesRequested),
    intendedTerritories: r.intendedTerritories,
    estimatedTimeline: undef(r.estimatedTimeline),
    additionalMessage: undef(r.additionalMessage),
    privacyAccepted: r.privacyAccepted,
    termsAccepted: r.termsAccepted,
    marketingOptIn: undef(r.marketingOptIn),
    linkedCompanyId: undef(r.linkedCompanyId),
    adminNote: undef(r.adminNote),
    decidedByUserId: undef(r.decidedByUserId),
    decidedAt: r.decidedAt?.toISOString(),
    createdAt: r.createdAt.toISOString(),
  };
}

/** Registration DTO -> Prisma write payload (shared by create and update). */
export function registrationWriteData(input: Registration, actorId: string | null) {
  return {
    reference: input.reference,
    status: input.status,
    legalName: input.legalName,
    tradingName: input.tradingName ?? null,
    companyType: input.companyType,
    companySubtype: input.companySubtype ?? null,
    website: input.website ?? null,
    country: input.country,
    countryCode: input.countryCode,
    region: input.region ?? null,
    city: input.city,
    address: input.address ?? null,
    postalCode: input.postalCode ?? null,
    vatNumber: input.vatNumber ?? null,
    registrationNumber: input.registrationNumber ?? null,
    mainActivity: input.mainActivity ?? null,
    companySize: input.companySize ?? null,
    marketsServed: input.marketsServed ?? [],
    preferredLanguage: input.preferredLanguage,
    preferredCurrency: input.preferredCurrency,
    timezone: input.timezone ?? null,
    contactFirstName: input.contactFirstName,
    contactLastName: input.contactLastName,
    contactJobTitle: input.contactJobTitle ?? null,
    contactDepartment: input.contactDepartment ?? null,
    contactEmail: input.contactEmail,
    contactPhone: input.contactPhone ?? null,
    contactMobile: input.contactMobile ?? null,
    contactLanguage: input.contactLanguage ?? null,
    reason: input.reason ?? null,
    existingContactPerson: input.existingContactPerson ?? null,
    intendedApplications: input.intendedApplications ?? [],
    productCategories: input.productCategories ?? [],
    samplesRequested: input.samplesRequested ?? null,
    intendedTerritories: input.intendedTerritories ?? [],
    estimatedTimeline: input.estimatedTimeline ?? null,
    additionalMessage: input.additionalMessage ?? null,
    privacyAccepted: input.privacyAccepted,
    termsAccepted: input.termsAccepted,
    marketingOptIn: input.marketingOptIn ?? null,
    linkedCompanyId: input.linkedCompanyId ?? null,
    adminNote: input.adminNote ?? null,
    decidedByUserId: input.decidedByUserId ?? null,
    decidedAt: input.decidedAt ? new Date(input.decidedAt) : null,
    updatedById: actorId,
  };
}
